// <auto-generated />
using System;
using ControlGastosApp.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlGastosApp.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250531232549_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControlGastosApp.Web.Models.Deposito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "descripcion");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "fecha");

                    b.Property<int>("FondoId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "fondoId");

                    b.Property<int?>("FondoMonetarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "monto");

                    b.HasKey("Id");

                    b.HasIndex("FondoMonetarioId");

                    b.ToTable("Depositos");
                });

            modelBuilder.Entity("ControlGastosApp.Web.Models.DetalleGasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "monto");

                    b.Property<int>("RegistroGastoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoGastoId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "tipoGastoId");

                    b.HasKey("Id");

                    b.HasIndex("RegistroGastoId");

                    b.HasIndex("TipoGastoId");

                    b.ToTable("DetallesGastos");

                    b.HasAnnotation("Relational:JsonPropertyName", "detalles");
                });

            modelBuilder.Entity("ControlGastosApp.Web.Models.FondoMonetario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "nombre");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "saldo");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "tipo");

                    b.HasKey("Id");

                    b.ToTable("FondosMonetarios");

                    b.HasAnnotation("Relational:JsonPropertyName", "fondoMonetario");
                });

            modelBuilder.Entity("ControlGastosApp.Web.Models.Gasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoGastoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoGastoId");

                    b.ToTable("Gasto");
                });

            modelBuilder.Entity("ControlGastosApp.Web.Models.Presupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Mes")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasAnnotation("Relational:JsonPropertyName", "mes");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "monto");

                    b.Property<int>("TipoGastoId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "tipoGastoId");

                    b.HasKey("Id");

                    b.HasIndex("TipoGastoId");

                    b.ToTable("Presupuestos");
                });

            modelBuilder.Entity("ControlGastosApp.Web.Models.RegistroGasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comercio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "comercio");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "fecha");

                    b.Property<int>("FondoId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "fondoId");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasAnnotation("Relational:JsonPropertyName", "observaciones");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "tipoDocumento");

                    b.HasKey("Id");

                    b.HasIndex("FondoId");

                    b.ToTable("RegistrosGastos");
                });

            modelBuilder.Entity("ControlGastosApp.Web.Models.TipoGasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "nombre");

                    b.HasKey("Id");

                    b.ToTable("TiposGasto");
                });

            modelBuilder.Entity("ControlGastosApp.Web.Models.Deposito", b =>
                {
                    b.HasOne("ControlGastosApp.Web.Models.FondoMonetario", "FondoMonetario")
                        .WithMany("Depositos")
                        .HasForeignKey("FondoMonetarioId");

                    b.Navigation("FondoMonetario");
                });

            modelBuilder.Entity("ControlGastosApp.Web.Models.DetalleGasto", b =>
                {
                    b.HasOne("ControlGastosApp.Web.Models.RegistroGasto", "RegistroGasto")
                        .WithMany("Detalles")
                        .HasForeignKey("RegistroGastoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlGastosApp.Web.Models.TipoGasto", "TipoGasto")
                        .WithMany()
                        .HasForeignKey("TipoGastoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroGasto");

                    b.Navigation("TipoGasto");
                });

            modelBuilder.Entity("ControlGastosApp.Web.Models.Gasto", b =>
                {
                    b.HasOne("ControlGastosApp.Web.Models.TipoGasto", "TipoGasto")
                        .WithMany("Gastos")
                        .HasForeignKey("TipoGastoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoGasto");
                });

            modelBuilder.Entity("ControlGastosApp.Web.Models.Presupuesto", b =>
                {
                    b.HasOne("ControlGastosApp.Web.Models.TipoGasto", "TipoGasto")
                        .WithMany("Presupuestos")
                        .HasForeignKey("TipoGastoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoGasto");
                });

            modelBuilder.Entity("ControlGastosApp.Web.Models.RegistroGasto", b =>
                {
                    b.HasOne("ControlGastosApp.Web.Models.FondoMonetario", "Fondo")
                        .WithMany()
                        .HasForeignKey("FondoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fondo");
                });

            modelBuilder.Entity("ControlGastosApp.Web.Models.FondoMonetario", b =>
                {
                    b.Navigation("Depositos");
                });

            modelBuilder.Entity("ControlGastosApp.Web.Models.RegistroGasto", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("ControlGastosApp.Web.Models.TipoGasto", b =>
                {
                    b.Navigation("Gastos");

                    b.Navigation("Presupuestos");
                });
#pragma warning restore 612, 618
        }
    }
}
